/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package giao_Dien;

import Repository.Repository_HDCT;
import Repository.Repository_HoaDonFillTen;
import entity.HDCT_entity;
import entity.Hoa_Don_FillTen_entity;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GIGABYTE
 */
public class Hoa_Don extends javax.swing.JInternalFrame {

    private DefaultTableModel dtm2;
    private DefaultTableModel dtm3;
    private Repository.Repository_HoaDonFillTen hdft = new Repository_HoaDonFillTen();
    private Repository_HDCT hdct = new Repository_HDCT();

    /**
     * Creates new form Hoa_Don
     */
    public Hoa_Don() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        setBorder(BorderFactory.createEmptyBorder());
        dtm2 = (DefaultTableModel) tbl_HoaDon.getModel();
        dtm3 = (DefaultTableModel) tbl_HDCT.getModel();
        FillHoaDon(hdft.getAlll());
        rdo_DaThanhToan.addActionListener(e -> timKiemHoaDon());
        rdo_ChuaThanhToan.addActionListener(e -> timKiemHoaDon());
    }

    private void FillHoaDon(ArrayList<Hoa_Don_FillTen_entity> list) {
        dtm2.setRowCount(0);
        for (Hoa_Don_FillTen_entity hdft : list) {
            Object[] rowdata = {
                hdft.getID_HoaDon(),
                hdft.getTen_KhachHang(),
                hdft.getTen_NhanVien(),
                hdft.getVoucher(),
                hdft.getNgayMua(),
                hdft.getTrangThai() ? "Đã thanh toán" : "Chưa thanh toán",
                hdft.getTong()
            };
            dtm2.addRow(rowdata);
        }
    }

    public void ShowGioHang(ArrayList<HDCT_entity> list) {
        dtm3.setRowCount(0);
        for (HDCT_entity hdct : list) {
            dtm3.addRow(new Object[]{
                hdct.getIDHoaDon(),
                hdct.getIDSanPham(),
                hdct.getTenSanPham(),
                hdct.getSoLuong(),
                hdct.getDonGia()
            });
        }
    }

    public void LoadHD() {
        FillHoaDon(hdft.getAlll());
    }

    private void timKiemHoaDon() {
        ArrayList<Hoa_Don_FillTen_entity> kiemTra = new ArrayList<>();
        boolean checkChuaThanhToan = rdo_ChuaThanhToan.isSelected();
        boolean checkDaThanhToan = rdo_DaThanhToan.isSelected();
        for (Hoa_Don_FillTen_entity hd : hdft.getAlll()) {
            boolean trangThai = hd.getTrangThai();
            if (checkChuaThanhToan && !trangThai) {
                kiemTra.add(hd);
            }
            if (checkDaThanhToan && trangThai) {
                kiemTra.add(hd);
            }
        }
        FillHoaDon(kiemTra);
    }
    public void show(int index) {
        Hoa_Don_FillTen_entity shd = hdft.getAlll().get(index);
        jcb_tenkhach.setText(shd.getTen_KhachHang());
        jcb_nhanVien.setText(shd.getTen_NhanVien());
        jcb_voucher.setText(String.valueOf(shd.getVoucher()));
        jcb_ngayMua.setText(shd.getNgayMua().toString());
        jcb_trangThai.setText(shd.getTrangThai() ? "Đã thanh toán" : "Chưa thanh toán");
        jcb_tong.setText(String.valueOf(shd.getTong()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_HoaDon = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_HDCT = new javax.swing.JTable();
        rdo_ChuaThanhToan = new javax.swing.JRadioButton();
        rdo_DaThanhToan = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcb_tenkhach = new javax.swing.JLabel();
        jcb_nhanVien = new javax.swing.JLabel();
        jcb_voucher = new javax.swing.JLabel();
        jcb_ngayMua = new javax.swing.JLabel();
        jcb_trangThai = new javax.swing.JLabel();
        jcb_tong = new javax.swing.JLabel();

        tbl_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id hóa đơn", "Khách hàng", "Nhân viên", "Voucher", "Ngày mua", "Trang thái", "Tổng giá"
            }
        ));
        tbl_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_HoaDon);

        tbl_HDCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID hdct", "ID", "Tên", "Số lượng", "Đơn giá"
            }
        ));
        jScrollPane2.setViewportView(tbl_HDCT);

        buttonGroup1.add(rdo_ChuaThanhToan);
        rdo_ChuaThanhToan.setText("Chưa thanh toán");

        buttonGroup1.add(rdo_DaThanhToan);
        rdo_DaThanhToan.setText("Đã thanh toán");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/refresh.png"))); // NOI18N
        jButton1.setText("Làm mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Khách hàng:");

        jLabel2.setText("Nhân viên:");

        jLabel3.setText("Voucher:");

        jLabel4.setText("Ngày mua:");

        jLabel5.setText("Trạng thái:");

        jLabel6.setText("Tổng giá:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_tenkhach)
                    .addComponent(jcb_nhanVien)
                    .addComponent(jcb_voucher)
                    .addComponent(jcb_ngayMua)
                    .addComponent(jcb_trangThai)
                    .addComponent(jcb_tong))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcb_tenkhach))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcb_nhanVien))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcb_voucher))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcb_ngayMua))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcb_trangThai))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcb_tong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(rdo_DaThanhToan)
                        .addGap(26, 26, 26)
                        .addComponent(rdo_ChuaThanhToan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdo_DaThanhToan)
                        .addComponent(rdo_ChuaThanhToan)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HoaDonMouseClicked
        // TODO add your handling code here:
        int idHoaDon = Integer.valueOf(tbl_HoaDon.getValueAt(tbl_HoaDon.getSelectedRow(), 0).toString());
        ShowGioHang(hdct.getAll(idHoaDon));
        int index = tbl_HoaDon.getSelectedRow();
        show(index);
    }//GEN-LAST:event_tbl_HoaDonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FillHoaDon(hdft.getAlll());
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jcb_ngayMua;
    private javax.swing.JLabel jcb_nhanVien;
    private javax.swing.JLabel jcb_tenkhach;
    private javax.swing.JLabel jcb_tong;
    private javax.swing.JLabel jcb_trangThai;
    private javax.swing.JLabel jcb_voucher;
    private javax.swing.JRadioButton rdo_ChuaThanhToan;
    private javax.swing.JRadioButton rdo_DaThanhToan;
    private javax.swing.JTable tbl_HDCT;
    private javax.swing.JTable tbl_HoaDon;
    // End of variables declaration//GEN-END:variables
}
