/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giao_Dien;

import javax.swing.JDesktopPane;

/**
 *
 * @author GIGABYTE
 */
public class Trang_Chu extends javax.swing.JFrame {

    private int idNhanVien;
    private boolean isManager;
    Nhan_Vien nv = new Nhan_Vien();
    San_Pham sp = new San_Pham();
    Khach_Hang kh = new Khach_Hang();
    Khuyen_Mai km = new Khuyen_Mai();
    Ban_Hang bh = new Ban_Hang();
    Voucher vc = new Voucher();
    Hoa_Don hd = new Hoa_Don();
    Thong_Ke tk = new Thong_Ke();

    //Voucher vc = new Voucher();
    /**
     * Creates new form Trang_Chu
     */
    public Trang_Chu() {
        initComponents();
        setLocationRelativeTo(null);

        nv.setVisible(false);
        jDesktopPane1.add(nv);

        sp.setVisible(false);
        jDesktopPane1.add(sp);

        kh.setVisible(false);
        jDesktopPane1.add(kh);

        km.setVisible(false);
        jDesktopPane1.add(km);

        bh.setVisible(false);
        jDesktopPane1.add(bh);

        vc.setVisible(false);
        jDesktopPane1.add(vc);

        hd.setVisible(false);
        jDesktopPane1.add(hd);

        tk.setVisible(false);
        jDesktopPane1.add(tk);
    }

   public void setChucVu(boolean isManager) {
        this.isManager = isManager;
        updateUIBasedOnRole();
    }



    private void updateUIBasedOnRole() {
        HoaDon.setEnabled(isManager);
        KhuyenMai.setEnabled(isManager);
        Voucher.setEnabled(isManager);
        NhanVien.setEnabled(isManager);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SanPham = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        NhanVien = new javax.swing.JButton();
        KhachHang = new javax.swing.JButton();
        KhuyenMai = new javax.swing.JButton();
        HoaDon = new javax.swing.JButton();
        BanHang = new javax.swing.JButton();
        Voucher = new javax.swing.JButton();
        Thong_Ke = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        SanPham.setBackground(new java.awt.Color(0, 102, 102));
        SanPham.setForeground(new java.awt.Color(255, 255, 255));
        SanPham.setText("Sản Phẩm ");
        SanPham.setBorder(null);
        SanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanPhamActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/z5620499176268_875206858b96ebe8346f2e060a1f1998.jpg"))); // NOI18N
        jLabel1.setText("SHOP BALO");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        NhanVien.setBackground(new java.awt.Color(0, 102, 102));
        NhanVien.setForeground(new java.awt.Color(255, 255, 255));
        NhanVien.setText("Nhân viên");
        NhanVien.setBorder(null);
        NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhanVienActionPerformed(evt);
            }
        });

        KhachHang.setBackground(new java.awt.Color(0, 102, 102));
        KhachHang.setForeground(new java.awt.Color(255, 255, 255));
        KhachHang.setText("Khách hàng ");
        KhachHang.setBorder(null);
        KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhachHangActionPerformed(evt);
            }
        });

        KhuyenMai.setBackground(new java.awt.Color(0, 102, 102));
        KhuyenMai.setForeground(new java.awt.Color(255, 255, 255));
        KhuyenMai.setText("Khuyến mãi");
        KhuyenMai.setBorder(null);
        KhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KhuyenMaiActionPerformed(evt);
            }
        });

        HoaDon.setBackground(new java.awt.Color(0, 102, 102));
        HoaDon.setForeground(new java.awt.Color(255, 255, 255));
        HoaDon.setText("Hóa đơn");
        HoaDon.setBorder(null);
        HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoaDonActionPerformed(evt);
            }
        });

        BanHang.setBackground(new java.awt.Color(0, 102, 102));
        BanHang.setForeground(new java.awt.Color(255, 255, 255));
        BanHang.setText("Bán hàng");
        BanHang.setBorder(null);
        BanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanHangActionPerformed(evt);
            }
        });

        Voucher.setBackground(new java.awt.Color(0, 102, 102));
        Voucher.setForeground(new java.awt.Color(255, 255, 255));
        Voucher.setText("Voucher");
        Voucher.setBorder(null);
        Voucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoucherActionPerformed(evt);
            }
        });

        Thong_Ke.setBackground(new java.awt.Color(0, 102, 102));
        Thong_Ke.setForeground(new java.awt.Color(255, 255, 255));
        Thong_Ke.setText("Thống kê");
        Thong_Ke.setBorder(null);
        Thong_Ke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Thong_KeActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã nhân viên:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KhuyenMai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Voucher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Thong_Ke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(315, 315, 315)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(KhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Voucher, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Thong_Ke, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SanPhamActionPerformed
        // TODO add your handling code here:
        nv.setVisible(false);
        sp.setVisible(true);
        kh.setVisible(false);
        km.setVisible(false);
        bh.setVisible(false);
        vc.setVisible(false);
        hd.setVisible(false);
        tk.setVisible(false);
        sp.LoadKM();
        sp.LoadSP();
    }//GEN-LAST:event_SanPhamActionPerformed

    private void NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhanVienActionPerformed
        // TODO add your handling code here:
        nv.setVisible(true);
        sp.setVisible(false);
        kh.setVisible(false);
        km.setVisible(false);
        bh.setVisible(false);
        vc.setVisible(false);
        hd.setVisible(false);
        tk.setVisible(false);
    }//GEN-LAST:event_NhanVienActionPerformed

    private void KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KhachHangActionPerformed
        // TODO add your handling code here:
        nv.setVisible(false);
        sp.setVisible(false);
        kh.setVisible(true);
        km.setVisible(false);
        bh.setVisible(false);
        vc.setVisible(false);
        hd.setVisible(false);
        tk.setVisible(false);
        kh.loadData();
    }//GEN-LAST:event_KhachHangActionPerformed

    private void KhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KhuyenMaiActionPerformed
        // TODO add your handling code here:
        nv.setVisible(false);
        sp.setVisible(false);
        kh.setVisible(false);
        km.setVisible(true);
        bh.setVisible(false);
        vc.setVisible(false);
        hd.setVisible(false);
        tk.setVisible(false);
    }//GEN-LAST:event_KhuyenMaiActionPerformed

    private void HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoaDonActionPerformed
        // TODO add your handling code here:
        nv.setVisible(false);
        sp.setVisible(false);
        kh.setVisible(false);
        km.setVisible(false);
        bh.setVisible(false);
        vc.setVisible(false);
        hd.setVisible(true);
        tk.setVisible(false);
        hd.LoadHD();
    }//GEN-LAST:event_HoaDonActionPerformed

    private void BanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BanHangActionPerformed
        // TODO add your handling code here:
        nv.setVisible(false);
        sp.setVisible(false);
        kh.setVisible(false);
        km.setVisible(false);
        bh.setVisible(true);
        vc.setVisible(false);
        hd.setVisible(false);
        tk.setVisible(false);
        bh.loadData();
        bh.LoadVC();
    }//GEN-LAST:event_BanHangActionPerformed

    private void VoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoucherActionPerformed
        // TODO add your handling code here:
        nv.setVisible(false);
        sp.setVisible(false);
        kh.setVisible(false);
        km.setVisible(false);
        bh.setVisible(false);
        vc.setVisible(true);
        hd.setVisible(false);
        tk.setVisible(false);
    }//GEN-LAST:event_VoucherActionPerformed

    private void Thong_KeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Thong_KeActionPerformed
        // TODO add your handling code here:
        nv.setVisible(false);
        sp.setVisible(false);
        kh.setVisible(false);
        km.setVisible(false);
        bh.setVisible(false);
        vc.setVisible(false);
        hd.setVisible(false);
        tk.setVisible(true);
        tk.LoadThongKe();
    }//GEN-LAST:event_Thong_KeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trang_Chu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trang_Chu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trang_Chu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trang_Chujbl_ma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trang_Chu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BanHang;
    private javax.swing.JButton HoaDon;
    private javax.swing.JButton KhachHang;
    private javax.swing.JButton KhuyenMai;
    private javax.swing.JButton NhanVien;
    private javax.swing.JButton SanPham;
    private javax.swing.JButton Thong_Ke;
    private javax.swing.JButton Voucher;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
